language: scala
scala:
- 2.13.5
script:
- sbt scalafmtCheckAll
- sbt ++$TRAVIS_SCALA_VERSION test
deploy:
  provider: heroku
  app: recibase-api
  api_key:
    secure: DqoilOwTUcKu2HHFXxGV2eT8hdhuFmu87cc5+obpV/uDIEkjVJACeKQNxzTwcehYReEln6of2Kv8GN2BUndY6L0qyJC9v7YfgnJxZD/Zt80vCJHDGqKQ46QeOQrqh148TIiG/74Y1Y9QZWLwZbNga2+1wL5hSBdbu09vhD/7IPYqoki/2nWjl25xtJd/+EzvB1d6ylYJOhqwvQ0rCTt/MfDU+Qs62g5pNx5MwdDR+y4CuEEJScbwfKgcuTIkYKEzAsjhpjvtARtwal1X3MVCEY7xrrBOPGY/bvTFSVceHx6njpRBpxdVBMdCX292Nae6+9y1LAo+eQdEfbW8fqd3k+PW5GKtN4I8CDy0J8RslQILID4WDOLTqCKToWqJeVv+pwSn25K04ydQZcHIHjEKB1eTK5VY9NGA0YJJwIlryUMz5rjy4oqcNompZz5N1+4wxPBhs4xtVxyFgXRjiANDzQtBbwuovJKOaLIXzNSdsegOVZuWXicmOfyCwDVFTuwtYzFvMNYWXe+ETA0Cg2hWc3aEDMHMVZLr32semme2ZmnDsne0KUqHE8y+IjS9T+00OrbBSEBTgYy7gT5iQ+amMpMHadieND4kWTSRj9nJrIbQSXfMUxmDoCKbghAxd5YPwEg0j7I5OddiyMj8uJgp8lIkla6yTHgZjHXjssE5gmk=
